# Generated by Django 2.1 on 2018-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(choices=[('CA', 'California'), ('GA', 'Georgia'), ('WA', 'Washinton')], default='CA', max_length=30),
        ),
    ]
